### PR TITLE
Scala 2.12.3

### PR DESCRIPTION
**Pull request by jw3**
- Bump Scala off the 2.12 RC to the latest
- Tut had to be bumped for 2.12
- Added 2.12 build to Travis

### CODE REVIEW

**Comment by jw3** [comment]
I'd say just publish 2.12 again once this is merged, adding to the existing 1.0.0 artifacts.

**Comment by metasim** [comment]
Thanks @jw3!

**Comment by metasim** [comment]
@jw3 Care to give it a spin?:
https://bintray.com/elderresearch/OSS/ssc/1.0.1

**Comment by jw3** [comment]
Looks to be working, thanks!

**Pull request merged**
